name: Frontend Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'npm'
          cache-dependency-path: 'fe/package-lock.json'

      - name: Install dependencies
        working-directory: fe
        run: npm ci

      - name: Lint
        working-directory: fe
        run: npm run lint || echo "No lint script found"
        
      - name: Build Next.js application
        working-directory: fe
        run: npm run build
        
      - name: Run tests
        working-directory: fe
        run: npm test || echo "No test script found"

      - name: Security audit
        working-directory: fe
        run: npm audit --production
        
  publish:
    runs-on: ubuntu-latest
    needs: build-test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'npm'
          cache-dependency-path: 'fe/package-lock.json'

      - name: Install dependencies
        working-directory: fe
        run: npm ci

      - name: Build and Push Docker
        uses: docker/build-push-action@v4
        with:
          context: ./fe
          file: ./fe/Dockerfile
          push: true
          tags: ghcr.io/sunnah-com/v3-frontend:latest
